---
tags:
- pdep
- guia4
- listas
- lambdas
- aritmetica
- pointFree
- ordenSuperior
- fold
- foldl
- tipos
layout: editor_right
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
